hostname = "minimal-box"
timezone = "UTC"
locale = "en_US.UTF-8"
stateVersion = "25.11"

[disk]
device = "/dev/sda"

[swap]
size = 1024

[networking]
ports = [22]

[docker]
enable = false

[sops]
secrets = []

[root]
sshKeys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEaT/b47r3sHQdrwhShHrw8XXVEaXN9WzQk5kOxu1y5R andre.abadesso@gmail.com",
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMh5PUo1BDe3MURD9g7EHO8OTq2bxerdAp2ICeYqy4CE andre@nixos",
]

[[users]]
name = "andre"
shell = "bash"
groups = ["wheel"]
sshKeys = [
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEaT/b47r3sHQdrwhShHrw8XXVEaXN9WzQk5kOxu1y5R andre.abadesso@gmail.com",
  "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMh5PUo1BDe3MURD9g7EHO8OTq2bxerdAp2ICeYqy4CE andre@nixos",
]

[openclaw]
enable = false
